[project]
name = 'panc_contrants'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.allowance_wallet]
path = 'contracts/allowance_wallet.clar'
clarity_version = 2
epoch = 2.5

[contracts.restricted_storage]
path = 'contracts/restricted_storage.clar'
clarity_version = 2
epoch = 2.5

[contracts.storage_incentives]
path = 'contracts/storage_incentives.clar'
clarity_version = 2
epoch = 2.5

[contracts.vote_receipt]
path = 'contracts/vote_receipt.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
